Added libraries and modified Makefile.
git-svn-id: https://www.prismmodelchecker.org/svn/prism/prism/branches/prism-games@6404 bbc10eb1-c90d-0410-af57-cb519fbb1720

diff --git a/prism/Makefile b/prism/Makefile
--- a/prism/Makefile
+++ b/prism/Makefile
@@ -254,6 +254,11 @@ endif
 CUDD_DIR =		$(shell if [ -d cudd ]; then echo cudd; else echo ../cudd; fi )
 #CUDD_DIR =		cudd
 
+# For PPL, we default either to ./ppl or, if that does not exist, ../ppl
+# To override, comment out the first line and use the second (or specify from the command-line)
+PPL_DIR =		$(shell if [ -d ppl ]; then echo ppl; else echo ../ppl; fi )
+#PPL_DIR =		ppl
+
 SRC_DIR =		src
 CLASSES_DIR =	classes
 OBJ_DIR =		obj
@@ -276,7 +281,7 @@ MAKE_DIRS = dd jdd odd dv prism mtbdd sparse hybrid parser settings userinterfac
 
 default: all
 
-all: cuddpackage prism
+all: cuddpackage untarpppl pplpackage prism
 
 cuddpackage: checks
 	@if [ "$(CUDD_DIR)" = "" ]; then echo "Error: Cannot find CUDD"; exit 1; fi
@@ -297,6 +302,30 @@ cuddpackageforce: checks
 	  $(MAKE) C="$(C)" CC="$(C)" CPP="$(CPP)" \
 	  XCFLAGS="$(CUDD_XCFLAGS)";
 
+untarppl:
+	cd .. && \
+	tar xzf ppl.tar.gz;
+
+pplpackage: checks
+	@if [ "$(PPL_DIR)" = "" ]; then echo "Error: Cannot find PPL"; exit 1; fi
+	@if [ ! -d "$(PPL_DIR)" ]; then echo "Error: Cannot find PPL"; exit 1; fi
+	@(if [ ! -h $(PPL_DIR) ]; then \
+	  echo Configuring ppl ...; \
+	  cd $(PPL_DIR) && \
+	  bash configure --prefix=$(pwd -P); \
+	  echo Making ppl ...; \
+	  cd $(PPL_DIR) && \
+	  $(MAKE) C="$(C)" CC="$(C)" CPP="$(CPP)"; \
+	  echo Installing ppl ...; \
+	  cd $(PPL_DIR) && \
+	  $(MAKE) install; \
+	  echo Linking ppl ...; \
+	  ln -s $(pwd -P)$(PPL_DIR)/lib/ppl/libppl_java.so $(LIB_DIR)/libppl_java.so; \
+	  ln -s $(pwd -P)$(PPL_DIR)/lib/ppl/ppl_java.jar $(LIB_DIR)/ppl_java.jar; \
+	else \
+	  echo Skipping ppl make since it is a symlink...; \
+	fi)
+
 prism: checks make_dirs bin_scripts
 
 make_dirs:
@@ -306,6 +335,7 @@ make_dirs:
 	  (cd src/$$dir && \
 	  $(MAKE) \
 	  CUDD_DIR="$(CUDD_DIR)" \
+	  PPL_DIR="$(PPL_DIR)" \
 	  SRC_DIR="$(SRC_DIR)" \
 	  CLASSES_DIR="$(CLASSES_DIR)" \
 	  OBJ_DIR="$(OBJ_DIR)" \
@@ -464,10 +494,13 @@ clean: checks
 
 celan: clean
 
-clean_all: checks clean_cudd clean
+clean_all: checks clean_cudd clean_ppl clean
 
 clean_cudd:
 	@(cd $(CUDD_DIR) && $(MAKE) distclean)
+
+clean_ppl:
+	@(cd $(PPL_DIR) && $(MAKE) distclean)
 
 clean_dd: checks
 	@(cd src/dd && $(MAKE) -s SRC_DIR="$(SRC_DIR)" CLASSES_DIR="$(CLASSES_DIR)" OBJ_DIR="$(OBJ_DIR)" LIB_DIR="$(LIB_DIR)" EXE="$(EXE)" LIBPREFIX="$(LIBPREFIX)" LIBSUFFIX="$(LIBSUFFIX)" clean)
